### ISSUE TITLE
Non utilizzare le maschere. Sempre converti il testo in vettore.

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#1]
Ciao @Bonandry !

Ti ho già detto di non utilizzare le maschere e di convertire il testo in vettore. Ho corretto alcune icone deformate di «apps/scalable».

**Comment by Bonandry** [comment]
le maschere dovrebbero essere del tema principale

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

Sì, ma perché molti utenti delle applicazioni scritte in QT e in KDE, come Dolphin, Latte Dock, ecc., vorranno utilizzare il tuo tema di icone, perciò, le maschere non sono compatibili con le applicazioni scritte in QT. Ti ho insegnato come risolvere il problema delle maschere.

Se vuoi continuare a utilizzare le maschere e non vuoi risolvere questo problema con le applicazioni scritte in QT, rispetto la tua decisione, ma devi esplicare agli utenti di non-Ubuntu.

**Comment by Bonandry** [comment]
non è che non li voglio risolvere è che non mi accorgo che ci sono!!! :D

**Comment by Bonandry** [comment]
comunque ho aggiunto altre icone, quando vuoi puoi pubblicarlo
p.s. ho fatto un grande cambiamento in gnome-beta, guardaci

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

> non è che non li voglio risolvere è che non mi accorgo che ci sono!!! :D

OK!

> comunque ho aggiunto altre icone, quando vuoi puoi pubblicarlo

Ti riferisci al Yaru++ o GNOME++?

> p.s. ho fatto un grande cambiamento in gnome-beta, guardaci

Le ho controllate. La maggior parte delle icone di `actions` e `apps` sono perfettamente e puramente Adwaita. Vado rilasciare la prossima settimana, perché gli amministratori d’OpenDesktop non permettono/consentono allo sviluppatore di aggiornare quotidianamente.

**Comment by gusbemacbe** [comment]
@Bonandry , posso ottimizzare le icone di `apps`? Per ridurre la dimensione dell'archivio.

**Comment by Bonandry** [comment]
ho aggiunto icone a YARU e ho fatto molti collegamenti e ho sostutuito le action in Gnome

**Comment by Bonandry** [comment]
ho notato che alcune icone perdono dei particolari quando vengono ottimizzate

**Comment by gusbemacbe** [comment]
Ah, non vado riottimizzarle.

**Comment by Bonandry** [comment]
si prova ma prima di pubblicare fammi controllare

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

> si prova ma prima di pubblicare fammi controllare

OK, vado creare la nuova branch/versione per evitare la perdita di particolarità.

Come io sono un longo utente di [Boxy SVG](https://boxy-svg.com/), [Figma](https://www.figma.com) e di [IGdm](https://igdm.me/), per favore, aggiungi le icone:

* boxy-svg
* figma
* igdm

**Comment by Bonandry** [comment]
ok

**Comment by Bonandry** [comment]
Aggiunti, controlla se ti sembrano buone

**Comment by gusbemacbe** [comment]
Adesso migliore. Vado creare la branch per testare l'ottimizzazione e analizzare la perdita di particolarità.

Anche non ti dimenticare di aggiungerle ai temi di icone GNOME++ e Suru++ Ubuntu.

**Comment by gusbemacbe** [comment]
@Bonandry 

Non vado ottimizzare fino che tu abbia tutto finito, poi vado ottimizzare e rilasciare. Quanfo finito, avvisami.

**Comment by Bonandry** [comment]
ok non carico più niente, ottimizza

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ho tutto ottimizzato, eccetto la cartella `categories/scalable`. Ho tutto analizzato, comparando alle icone originali. Ci non è nessuna perdita di particolarità.

Molte icone sulla cartella `categories/scalable` sono deformate a causa della maschera in due branch `gusbemacbe` (ottimizzato) alla sinistra e `master` (originale) alla destra. Vedi:

![image](https://user-images.githubusercontent.com/2257024/57995036-6635dd80-7a96-11e9-944e-75779fe5c504.png)

Sto lavorando per correggerle.

**Comment by gusbemacbe** [comment]
Migliorato:

![image](https://user-images.githubusercontent.com/2257024/57995536-fe34c680-7a98-11e9-8612-d33590250a5f.png)

**Comment by gusbemacbe** [comment]
C'è un'icona deformata:

![image](https://user-images.githubusercontent.com/2257024/57998742-22989f00-7aa9-11e9-9cb6-4d351b1327d4.png)

**Comment by gusbemacbe** [comment]
Migliorato:

![image](https://user-images.githubusercontent.com/2257024/57999292-44932100-7aab-11e9-8e03-e4bf982d49fa.png)

**Comment by Bonandry** [comment]
penso di avere risolto

**Comment by gusbemacbe** [comment]
Sì, @Bonandry 

* Ho tutto ottimizzato, tutto analizzato, tutto comparato la sinistra e la destra, poi ci non è nessuna perdita di particolarità. 
* Ho ottimizzato, corretto i colori erronei e le icone deformate di `categories`, `mimetypes` e `places`. Ho tutto analizzato e comparato, nessuna perdita di particolarità.

**Comment by Bonandry** [comment]
ok !! si può rilasciare

**Comment by gusbemacbe** [comment]
Ancora manca un poco. La cartella `status/symbolic`, e README. 

Non hai bisogno di correggere le icone deformate adesso, ho già tutto corretto prima.

**Comment by Bonandry** [comment]
se ancora non lo hai pubblicato devo aggiungere le icone per evolution

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Pronto. Ho aggiornato le tue icone per Evolution. Ho appena rilasciato sull'OpenDesktop. 

Rimuove la cartella `yaru-plus` sulla cartella `Documenti/Github` del tuo computer e esegui il commando:

```
git clone -b beta --single-branch https://github.com/Bonandry/yaru-plus
```

**Comment by Bonandry** [comment]
ciao @gusbemacbe si ho visto e ho già scaricato la versione beta
come sempre, ottimo lavoro
