### ISSUE TITLE
Nautilus icons

### ISSUE THREAD

**Issue by vinay-gujar** [Bonandry/yaru-plus#11]
![Screenshot from 2019-06-01 15-22-52](https://user-images.githubusercontent.com/35658725/58746905-8647a280-8481-11e9-9264-cb3b64297247.png)

Nautilus uses the symbolic icons instead of the intended orange icons for folders and other files.
Is there any fix for this? Thanks!

**Comment by Bonandry** [comment]
![Schermata da 2019-07-16 18-36-08](https://user-images.githubusercontent.com/7957697/61312463-c330e400-a7f8-11e9-9b68-0b916009b41b.png)
