### ISSUE TITLE
[request] Minecraft, Dconf-Editor, HardInfo

### ISSUE THREAD

**Issue by DarthWound** [Bonandry/yaru-plus#13]
Hello, thank you for this icon set.

An icon for `minecraft` and `minecraft-launcher` would be great, one for `hardinfo` too. Also, if you can improve the `dconf-editor` icon by using the default red magnifier, like what you did in Suru++.

**Comment by gusbemacbe** [comment]
@Bonandry assigned.
@Bonandry designato.

**Comment by Bonandry** [comment]
added icon minecraft, minecraft-launcher, hardinfo and improved icons dconf-editor

**Comment by DarthWound** [comment]
Waw thank you that was quick!
Keep up the good work :)

**Comment by gusbemacbe** [comment]
@DarthWound 

I have just released a new official version. Please upgrade your icons theme

**Comment by DarthWound** [comment]
@gusbemacbe 
Yeah thank you :+1: but don't worry I often check and update my themes.

There's an issue, all arrows are replaced by RSS icon in GNOME Shell.
![rssarrows](https://user-images.githubusercontent.com/1771322/66922612-ad190680-f027-11e9-8aa7-184c8e013a78.png)

**Comment by gusbemacbe** [comment]
@DarthWound 

Je vais investiguer ça.

**Comment by gusbemacbe** [comment]
Hi @SmartFinn and @Feitchmeier!

I have been searching the RSS icon in the folders `actions` and `status`, but I did not find.

The RSS icon is only in the folders `apps`. I check the list of RSS symlinked icons, but they do not seem to be left arrow and right arrow icons.

**Comment by gusbemacbe** [comment]
S'il vous plaít, testez la *branch* `beta`, @DarthWound !

Sorry, @SmartFinn and @Feichtmeier, I found, but I still need a command. I am waiting for somebody's answer to my question at the forum.

**Comment by DarthWound** [comment]
I see arrows now, but they are ~2x bigger than the normal ones, and there's only the right-side.

![Capture d’écran de 2019-10-18 14-35-50](https://user-images.githubusercontent.com/1771322/67094915-06fb0700-f1b5-11e9-9727-c9133d571051.png)

PS: please keep writing in english for me :)

**Comment by gusbemacbe** [comment]
OK, @DarthWound , I will write in ENglish, alhtough I be a French-speaking since 9 years. 

I think I will have to remove the pan icon, or I will check the original Yaru icons theme.

**Comment by gusbemacbe** [comment]
@DarthWound !

Please test with the branch `beta`.

**Comment by DarthWound** [comment]
> OK, @DarthWound , I will write in ENglish, alhtough I be a French-speaking since 9 years.
Yeah but it's better for everyone if we keep talking in English :)
For example when you upload new commits or reply to people in Italian, I'm lost :smile: 

> @DarthWound !
> Please test with the branch `beta`.
It seems that using the beta branch solved this issue, arrows are ok now.

**Comment by gusbemacbe** [comment]
> For example when you upload new commits or reply to people in Italian, I'm lost

For @Bonandry to understand what I was doing. 

> It seems that using the beta branch solved this issue, arrows are ok now.

GReat!

**Comment by gusbemacbe** [comment]
Are arrows OK in the WiFi pop-up, @DarthWound ?

**Comment by DarthWound** [comment]
Yes, arrows are fine in date-menu and status-menu.

**Comment by gusbemacbe** [comment]
Great, @DarthWound ! I am still waiting for @btd1337 to test the arrows and the Slack icon. 

As you are a Void user. Is there Void site similar to Arch Linux's AUR site? I want to build my own icons theme for Void users to install without needing to come to the repos, so they will receive the updates automatically.

**Comment by DarthWound** [comment]
There's nothing like AUR in Void, but it's quite easy to create a package and add it in the official repos, everything's done in GitHub here: https://github.com/void-linux/void-packages

You could even open an issue to request a package of your icon theme.

I use Yaru++ on Ubuntu _(with Void I use [my modified Papirus set](https://alkusin.net/voidlinux/en#theme))_ and I don't mind updating manually, as I don't like PPAs. And I customize it a bit using a script, if you are curious about it there it is:
```
wget -qO- https://raw.githubusercontent.com/Bonandry/yaru-plus/master/install.sh | sh
cd /usr/share/icons/Yaru++/actions/symbolic/
sudo mv window-restore-symbolic.svg window-restore-symbolic.svg.bak
sudo wget -O window-restore-symbolic.svg https://alkusin.net/ubuntu/leftsidemax.svg
sudo mv view-app-grid-symbolic.svg view-app-grid-symbolic.svg.bak
sudo wget -O view-app-grid-symbolic.svg https://alkusin.net/ubuntu/launcher.svg
cd /usr/share/icons/Yaru++/apps/scalable/
sudo ln -sfnr hardinfo.svg /usr/share/hardinfo/pixmaps/logo.png
```
What it does: download and install Yaru++, change window-restore icon for leftside use, change app-grid icon to Ubuntu logo, and symlink hardinfo icon because it is "hardcoded".

**Comment by gusbemacbe** [comment]
> There's nothing like AUR in Void, but it's quite easy to create a package and add it in the official repos, everything's done in GitHub here: void-linux/void-packages

I have just seen https://github.com/void-linux/void-packages/blob/master/srcpkgs/papirus-icon-theme/template

Too easy. 

I visited your blog, and read everything. But I think that not everybody in the Void world is going to your own script, right?

> Change window-restore icon for left-side use, change app-grid icon to Ubuntu logo

Would you suggest me to replace the icons? I understand it is from your own script, but I am not sure if I should replace these icons in the repo.

**Comment by DarthWound** [comment]
No don't change the icons, it was just to show you what I do. Default Ubuntu behaviour is window controls at rightside nowadays, so keep it like that.

**Comment by gusbemacbe** [comment]
Hello @DarthWound !

Thank you for explaining!

@btd1337 has just tested, the wrong arrows in the date menu remain. He guessed you use the default GNOME Shell theme, but he uses another.

Please test with the theme https://github.com/monday15/lounge-gtk-theme, and see the Yaru++ affects the arrows in the date and status pop-up.

**Comment by DarthWound** [comment]
Just tried in a fresh install of Ubuntu 19.10 (GNOME 3.34) in a VM, arrows are fine using the beta channel of Yaru++ and Lounge theme.

**Comment by gusbemacbe** [comment]
@DarthWound , yeah, he used the wrong branch, and switched to the beta branch, it worked for him. As it is solved, I am going to close it and merge the beta branch into the master.
