### ISSUE TITLE
Popcorn icon error

### ISSUE THREAD

**Issue by btd1337** [Bonandry/yaru-plus#15]
@gusbemacbe Popcorn icon has the same error reported [in here](https://github.com/Bonandry/adwaita-plus/issues/21).

![Captura de tela de 2019-09-12 18-58-34](https://user-images.githubusercontent.com/11943860/64825813-f55e8800-d594-11e9-9158-12e2e72accc6.png)

**Comment by Bonandry** [comment]
I think I have solved it

**Comment by gusbemacbe** [comment]
Olá @btd1337 

Por favor, testa. 

Se não funciona, farei no Figma. Inkscape causa muitos bugs nos ícones, como certas funções nem suportadas no KDE.

@Bonandry 

Ho chieso @btd1337 di testarla. Si l'icona che hai modificato recentemente non fuz\nziona, devo farla sul Figma, perché Inkscape causa molti *bug* nelle icone.

**Comment by btd1337** [comment]
Problema corrigido. Muito obrigado pelo seu ótimo trabalho a frente da comunidade! 👏

![Captura de tela de 2019-09-13 18-25-16](https://user-images.githubusercontent.com/11943860/64895769-e559ad80-d653-11e9-90d1-295c438c1e15.png)

**Comment by gusbemacbe** [comment]
@Bonandry, il problema è risolto. Funziona adesso.
