### ISSUE TITLE
Icons Request [2]

### ISSUE THREAD

**Issue by btd1337** [Bonandry/yaru-plus#16]
- [x] **Qt Assistant**
Comment=Shows Qt documentation and examples
Icon=assistant
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/qt-assistant.svg)

- [x] **E-book Editor**
Comment=Edit E-books in various formats
Icon=calibre-ebook-edit
[Icon Link](https://github.com/kovidgoyal/calibre/blob/master/icons/ebook-edit.ico)

- [x] **E-book Viewer**
Comment=Viewer for E-books in all the major formats
Icon=calibre-viewer
[Icon Link](https://github.com/kovidgoyal/calibre/blob/master/icons/viewer.ico)

- [x] **Calibre**
Comment=E-book library management: Convert, view, share, catalogue all your e-books
Icon=calibre-gui
[Icon Link](https://github.com/kovidgoyal/calibre/blob/master/icons/calibre.png)

- [x] **Manage Printing**
Comment=CUPS Web Interface
Comment[it]=Interfaccia web di CUPS
Icon=cups
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/cups.svg)

- [x] **Qt Designer**
Comment=Design GUIs for Qt applications
Icon=QtProject-designer
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/qtdesigner.svg)

> Please, the Electron versions uses the same name in the system, therefore try use different color versions to differentiate them.
> 
> [IT] Per favore, le versioni di Electron usano lo stesso nome nel sistema, quindi prova a usare versioni di colore diverso per differenziarle.

- [x] **Electron 2**
Icon=electron2
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/electron2.svg)

- [x] **Electron 3**
Icon=electron
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/electron.svg)

- [x] **Electron 4**
Icon=electron4
[Icon Link]()

- [x] **EmulationStation**
Comment=Emulationstation
Icon=emulationstation
[Icon Link](https://github.com/Aloshi/EmulationStation/blob/master/data/es_icon.ico)

- [x] **GCleaner**
Comment=A Cleaner for the GNU/Linux Operating System
Icon=gcleaner
[Icon Link](https://github.com/gcleaner/gcleaner-vala/blob/master/data/icons/128/gcleaner.svg)

- [x] **ICC Profile Installer**
Comment=Install ICC profiles
Comment[it]=Installa profili ICC
Icon=application-vnd.iccprofile
[Icon Link]()

- [x] **GdaBrowser**  | **Navigatore del database**
Comment=Browse your database's contents
Comment[it]=Scorri il contenuto del database
Icon=gda-browser-5.0
[Icon Link]()

- [x] **Gda Control Center**  | **Centro di controllo accesso database**
Comment=Configure your database access environment
Comment[it]=Configurare l'ambiente d'accesso del proprio database
Icon=gda-control-center
[Icon Link]()

- [x] **Glade**  | **Disegnatore di interfacce**
Comment=Create or open user interface designs for GTK+ applications
Comment[it]=Crea o apre disegni di interfaccia utente per applicazioni GTK+
Icon=glade
[Icon Link]()

- [x] **Network Tools**  | **Strumenti per informazioni di rete**
Comment=View information about your network
Comment[it]=Mostra le informazioni sulla rete
Icon=gnome-nettool
[Icon Link](https://gitlab.gnome.org/GNOME/gnome-nettool/blob/master/pixmaps/gnome-nettool.png)

- [x] **Network Workgroup**
Comment=Control how you connect to the Internet
Comment[it]=Regola la connessione a Internet
Icon=network-workgroup
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/rete.svg)

- [x] **Personal File Sharing**
Comment=Launch Personal File Sharing if enabled
Comment[it]=Avvia la condivisione di file personali se abilitata
Icon=folder-remote
[Icon Link](https://github.com/zayronxio/Mojave-CT/blob/master/places/128/folder-html.svg)

- [x] **Green Recorder**
Comment=Record your desktop easily using a simple GUI
Icon=green-recorder
[Icon Link](https://github.com/foss-project/green-recorder/blob/master/data/green-recorder.png)

- [x] **Grub Customizer**
Comment=Customize the bootloader (GRUB2 or BURG)
Icon=grub-customizer
[Icon Link](https://github.com/mdeguzis/grub-customizer/blob/master/misc/icons/128x128.png)

- [x] **HP Device Manager**
Comment=View device status, ink levels and perform maintenance.
Icon=hp_logo
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/hp.svg)

- [x] **SUSE Studio Imagewriter**
Icon=imagewriter
[Icon Link](https://github.com/openSUSE/imagewriter/blob/master/icons/128x128/imagewriter.png)

- [x] **Code**  | **Editor di file sorgenti**
Comment=Edit code files
Comment[it]=Modifica file sorgenti
Icon=io.elementary.code
[Icon Link](https://github.com/elementary/code/blob/master/data/icons/64/io.elementary.code.svg)

- [x] **OpenJDK Java 10**
Comment=OpenJDK Java 10 Runtime
Icon=java10-openjdk
[Icon Link](https://image.flaticon.com/icons/svg/226/226777.svg)

- [x] **Kazam**  | **Strumento per registrare video e catturare schermate**
Comment=Record a video or take a screenshot of your screen
Comment[it]=Registra un video o cattura una schermata del desktop
Icon=kazam
[Icon Link](https://github.com/hzbd/kazam/blob/master/data/icons/128x128/apps/kazam.png)

- [x] **Klavaro**  | **Un altro programma per imparare ad usare la tastiera**
Comment=A very flexible and efficient touch typing tutor.
Comment[it]=Un programma per imparare ad usare la tastiera molto flessibile ed efficiente.
Icon=klavaro
[Icon Link](https://github.com/cbrnix/Newaita/blob/master/Newaita/apps/64/klavaro.svg)

- [x] **Komorebi**
Comment=Parallax backgrounds manager
Icon=komorebi
[Icon Link](https://github.com/cheesecakeufo/komorebi/blob/master/data/Icons/komorebi.svg)

- [x] **Mark Text**
Comment=Next generation markdown editor
Icon=marktext
[Icon Link](https://github.com/marktext/marktext/blob/develop/resources/icons/128x128/marktext.png)

- [x] **Master PDF Editor**
Comment=Edit your PDF and XPS files
Icon=masterpdfeditor
[Icon Link](https://github.com/pisilinux/pisilife-2/blob/master/master-pdf-editor/files/masterpdfeditor5.png)

- [x] **MySQL Workbench**
Comment=MySQL Database Design, Administration and Development Tool
Icon=mysql-workbench
[Icon Link](https://cloud.githubusercontent.com/assets/6188052/20116784/b3124190-a5cb-11e6-9472-85f17f196023.png)

- [x] **Color picker**
Comment=Choose colors from the picker or the screen
Icon=nl.hjdskes.gcolor3
[Icon Link](https://github.com/Hjdskes/gcolor3/blob/master/data/nl.hjdskes.gcolor3.svg)

- [x] **Gnome Boxes**  | **Visualizzatore/Gestore di macchine virtuali**
Comment=View and use virtual machines
Comment[it]=Visualizza e usa macchine virtuali
Icon=org.gnome.Boxes
[Icon Link](https://gitlab.gnome.org/GNOME/gnome-boxes/blob/master/data/icons/gnome-boxes.svg)

- [x] **Gnome Devhelp**  | **Esplorazione documentazione API**
Comment=A developer tool for browsing and searching API documentation
Comment[it]=Uno strumento per sviluppatori per esplorare e cercare la documentazione delle API
Icon=org.gnome.Devhelp
[Icon Link](https://gitlab.gnome.org/GNOME/devhelp/blob/master/data/icons/scalable/org.gnome.Devhelp.svg)

- [x] **Gnome Dictionary**
Comment=Check word definitions and spellings in an online dictionary
Comment[it]=Controlla definizioni e ortografia di parole su un dizionario in linea
Icon=accessories-dictionary
[Icon Link](https://gitlab.gnome.org/GNOME/gnome-dictionary/blob/master/data/gnome-dictionary.svg)

- [x] **FeedReader**  | **Client RSS**
Comment=Read feeds from web services
Comment[it]=Leggi feed dai servizi web
Icon=org.gnome.FeedReader
[Icon Link](https://github.com/jangernert/FeedReader/blob/master/data/application-icons/hicolor/128x128/apps/org.gnome.FeedReader.svg)

- [x] **Polari**
Comment=An Internet Relay Chat Client for GNOME
Comment[it]=Un programma IRC per GNOME
Icon=org.gnome.Polari
[Icon Link](https://gitlab.gnome.org/GNOME/polari/blob/master/data/icons/hicolor/scalable/apps/org.gnome.Polari.svg)

- [x] **Pomodoro**
Comment=A simple time management utility
Comment[it]=Una semplice utility per la gestione del tempo
Icon=gnome-pomodoro
[Icon Link](https://github.com/codito/gnome-pomodoro/blob/master/data/icons/256x256/gnome-pomodoro.png)

- [x] **Sysprof**  | **Profilatore**
Comment=Profile an application or entire system.
Comment[it]=Profila un'applicazione o l'intero sistema.
Icon=org.gnome.Sysprof
[Icon Link](https://gitlab.gnome.org/GNOME/sysprof/blob/master/data/icons/scalable/apps/org.gnome.Sysprof.svg)

- [x] **pCloud**
Comment=pCloud Drive Client built using electron and node.js. Distributed with AppImage.
Icon=pcloud
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/pcloud.svg)

- [x] **pgModeler**
Comment=A CASE tool for modeling PostgreSQL databases
Icon=pgmodeler
[Icon Link](https://pgmodeler.io/img/pgmodeler_logo.png)

- [x] **Sigil**
Comment=ePUB file editor
Icon=sigil
[Icon Link](https://www.macupdate.com/images/icons256/33395.png)

- [x] **Slack**
Comment=Slack Desktop
Icon=slack
[Icon Link](https://www.vectorlogo.zone/logos/slack/slack-icon.svg)

- [x] **SmartGit**
Comment=Graphical Git/Hg client
Icon=smartgit
[Icon Link](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/smartgit.svg)

- [x] **StarUML**
Comment=A sophisticated software modeler
Icon=staruml
[Icon Link](https://avatars1.githubusercontent.com/u/7642181?s=200&v=4)

- [x] **SVG Cleaner**
Comment=Batch, tunable SVG cleaning program
Icon=svgcleaner
[Icon Link](https://github.com/RazrFalcon/svgcleaner-gui/blob/master/icons/svgcleaner.ico)

- [x] **TeXstudio**
Comment=LaTeX development environment
Icon=texstudio
[Icon Link](https://cn.opendesktop.org/cache/85x85-crop/img/2/9/c/5/ca8e3c6bab236d6e98a8fa534dd76d68d3b4.png)

- [x] **Oracle VM VirtualBox**
Comment=Run several virtual systems on a single host computer
Comment[it]=Esegui più macchine virtuali su un singolo computer
Icon=virtualbox
[Icon Link](https://upload.wikimedia.org/wikipedia/commons/d/d5/Virtualbox_logo.png)

- [x] **Youtube-dl GUI**
Comment=GUI for youtube-dl downloader
Icon=youtube-dl-gui
[Icon Link](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/data/icons/hicolor/128x128/apps/youtube-dl-gui.png)

- [x] **Zenmap**
Comment=A cross-platform GUI for the Nmap Security Scanner.
Icon=zenmap
[Icon Link](http://www.iconarchive.com/show/flatwoken-icons-by-alecive/Apps-Zenmap-icon.html)

- [x] **Y Cutter**
Icon=chrome-opngmganjdbkepnmaakokoicipolgaeh-Default
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/y-cutter.svg)

**Comment by Bonandry** [comment]
Fatte e caricate (y)

**Comment by btd1337** [comment]
Un ottimo lavoro! Mancava solo l'icona `network-workgroup`.

**Comment by Bonandry** [comment]
l'icona network-workgroup era già persente nella cartella places

**Comment by btd1337** [comment]
Mi dispiace, stavo usando Suru ++ Places.

Grazie!
