### ISSUE TITLE
Gnome 3.34

### ISSUE THREAD

**Issue by Amathadius** [Bonandry/yaru-plus#17]
Some icons doesn't work anymore since 3.34.

Tilix
Gedit
Chromium
Gnome-tweaks
Discord
Cheese

And many more.

**Comment by gusbemacbe** [comment]
Salut @Amathadius !

C'est un *bug* du `share-mime-info` comme @btd1337 nous a informé dans l'issue #14. Voyez la référence ; https://bugzilla.redhat.com/show_bug.cgi?id=1751549

Vous devez faire *downgrade* de la version 1.13 du `share-mime-info` pour 1.12.

Ou je dois nettoyer le thème d'icônes avec SVG Cleaner comme @btd1337 nous a suggéré.

**Comment by gusbemacbe** [comment]
@Amathadius !

Prêt ! Voici la nuovelle version ici.

**Comment by Amathadius** [comment]
Parfait, merci.
