### ISSUE TITLE
Fa' poche icone colorate di applicazioni e inviamele qui. 

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#20]
Ciao @Bonandry !

Per favore, fa le icone colorate di applicazioni in puro stile di Yaru++. Inviamele qui. 

[apps-scalable.zip](https://github.com/Bonandry/yaru-plus/files/3720199/apps-scalable.zip)

**Comment by Bonandry** [comment]
[apps.zip](https://github.com/Bonandry/yaru-plus/files/3720750/apps.zip)
ecco

**Comment by gusbemacbe** [comment]
Grazie!
