### ISSUE TITLE
Action Colored

### ISSUE THREAD

**Issue by Bonandry** [Bonandry/yaru-plus#21]
@gusbemacbe cosa ne pensi?
![Schermata da 2019-10-12 18-02-08](https://user-images.githubusercontent.com/7957697/66704912-b7ce5580-ed20-11e9-90f1-111a589a9faf.png)
![Schermata da 2019-10-12 18-10-33](https://user-images.githubusercontent.com/7957697/66704913-b866ec00-ed20-11e9-8594-b533101e6c88.png)
![Schermata da 2019-10-12 18-24-37](https://user-images.githubusercontent.com/7957697/66704914-b866ec00-ed20-11e9-81f5-2fd4332be821.png)
![Schermata da 2019-10-12 18-36-21](https://user-images.githubusercontent.com/7957697/66704915-b866ec00-ed20-11e9-80d1-6bdc790cadbb.png)
![Schermata da 2019-10-12 18-37-43](https://user-images.githubusercontent.com/7957697/66704917-b866ec00-ed20-11e9-8c28-07a9dcc966e4.png)

**Comment by gusbemacbe** [comment]
Ciao @Bonandry!

Le icone di 16 e 22 px fatte dagli sviluppatori di Ubuntu, sono troppo brutte, sono troppo simili alle vecchie icone di Adwaita dei anni 1990. 

Ma icone di 24px e 32px sono belle e bene leggibili.

Come Adwaita, Suru e Yaru sono sotto la licenza GPL, puoi sostituire le icone colorate di 16, 22 e 24 px per le icone monocromatiche come hai già fatto.

**Comment by Bonandry** [comment]
anche per me le monocromatiche sono migliori

**Comment by gusbemacbe** [comment]
Sì, le piccole icone monocromatiche sono molto bene leggibili di le piccole icone colorate. Nessun gli piacciono le icone degli anni 1990. Loro vogliono le nuove e moderne icone.
