### ISSUE TITLE
Teste di nuova verisone!

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#22]
Ciao @Bonandry !

Per favore, testa la nuova versione. Se non sei felice con alcune icone, per favore, modificale, comprimile e inviamele qui. 

Dopo vado copiare le tue nuove icone della tua versione attuale. 

[Yaru++.zip](https://github.com/Bonandry/yaru-plus/files/3721004/Yaru%2B%2B.zip)

**Comment by Bonandry** [comment]
Ciao @gusbemacbe 
mancano i collegamenti, vuoi rilasciare questa versione? 
per me va bene (y)

**Comment by gusbemacbe** [comment]
Questa versione = la mia o la tua? Quali i collegamenti mancano?

**Comment by Bonandry** [comment]
nella tua versione mancano i collegamenti delle 24 e 32 e nelle scalable

**Comment by gusbemacbe** [comment]
Di quali le cartelle? Io ho visto 24 e 32 nelle cartelle `apps`, `devices`, `mimetypes` e `places`.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Per favore rimuover la cartella del Yaru++ dove hai salvato. Scarica con il commando nel terminale:

```
cd "dove hai salvato la cartella"
git clone -b beta --single-branch https://github.com/Bonandry/yaru-plus`
```
