### ISSUE TITLE
Icons request - More folder icons

### ISSUE THREAD

**Issue by Amathadius** [Bonandry/yaru-plus#25]
It would be nice if there were more different icons for folders, for instance :
steam-folder
fonts-folder
git-folder
config-folder
icon/theme-folder
...

**Comment by gusbemacbe** [comment]
Salut @Amathadius !

Je vais les ajouter dans la prochaine version. Je vais dire l'Andrea de ne les en faire, parce qu'il n'en a pas de cette expérience.

Yaru++ et [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu) sont très pareils dans le cas de dossiers. Vous pouvez copier le dossier "places" du Suru++ pour écraser le dossier "places" du Yaru++. 

Observez que le répo Suru++ Dossiers est très démodé, mais vous pouvez modifier pour donner du soutien au Yaru++. 

Olá @btd1337!

Aderir-los-ei na próxima versão. Direi ao Andrea de não fazer isso porque ele não tem experiência disso. 

Yaru++ e [Suru++ Ubuntu](https://github.com/Bonandry/suru-plus-ubuntu) são muito parecidos no caso de pastas. Podes copiar a pasta "places" do Suru++ para sobrescrever a pasta "places" do Yaru++. 

Observa que o repositório Suru++ Pastas está muito desactualizado, mas podes modificá-lo para torná-lo compatível com o Yaru++.

**Comment by Bonandry** [comment]
@gusbemacbe ma queste cartelle sono da fare?

**Comment by gusbemacbe** [comment]
@Bonandry 

Cartelle con icone (config, font, git, gnome, onedrive, vscode, ecc.) e cartelle colorate con il suffisso del colore, basate sul Papirus, per esempio:

![image](https://user-images.githubusercontent.com/2257024/67263629-0b5a4500-f47f-11e9-8a14-569ad40b7e74.png)

folder (standard)
folder-azzuro
folder-giallo
folder-rosso
folder-git (standard)
folder-git-azzuro
folder-git-giallo
folder-git-rosso
folder-vscode (standard)
folder-vscode-azzuro
folder-vscode-giallo
folder-vscode-rosso

I colori delle cartelle e delle icone nelle cartelle sono generate correttamente con un Shell Script, creando correttamente i collegamenti, puoi vedere l'esempio di generazione di colori delle cartelle di Adwaita++: https://github.com/Bonandry/gnome-plus-beta-privato/blob/master/tools/build_color_folders.sh. Puoi controllare `Adwaita++/places/scalable` e capirai. 

Ma non hai questa experienzia, lasciale con me.

**Comment by DarthWound** [comment]
Any news about the new folders _(I'm interested by the steam-folder)_?

By the way, are you gonna update the stable branch soon?

**Comment by gusbemacbe** [comment]
@Amathadius and @DarthWound !

The colourful folders, including GitHub and Steam, are ready. It is on the branch `gusbemacbe`.

**Comment by gusbemacbe** [comment]
Ready, @Amathadius and @DarthWound!

It is on the branch `gusbemacbe` and please, use `Yaru++ Scalable`.

**Comment by Amathadius** [comment]
It doesn't work at all

**Comment by gusbemacbe** [comment]
@Amathadius 

:gb: I am discharged and return to work with Yaru++. Can I know what did not work for you, @Amathadius ?
:fr: Je suis récupéré et retourne à travailler avec le project Yaru++. Puis-je savoir ce quoi n'a pas fonctionné pour toi, @Amathadius ?

**Comment by gusbemacbe** [comment]
@Amathadius and @DarthWound

I realised I forgot of updating the repo, including the colourful folders before the coronavirus outbreak. I am very sorry. I have just updated.

**Comment by Amathadius** [comment]
I don't understand. It still doesn't here. And now it's the new (ugly?) folder icons with even less possibility than before.

**Comment by gusbemacbe** [comment]
@Amathadius 

What does it not have yet?
What icons did you find ugly?
