### ISSUE TITLE
Nuovo logo per la versione 3.0

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#31]
Ciao @Bonandry !

Quali un dei loghi preferisci?

![logo-alt-1](https://user-images.githubusercontent.com/2257024/67272967-f1772d00-f493-11e9-884a-08eb6745d6c5.png)

![logo-alt-2](https://user-images.githubusercontent.com/2257024/67272988-fb009500-f493-11e9-8e17-50299e74e545.png)

![logo-alt-3](https://user-images.githubusercontent.com/2257024/67273400-bc1f0f00-f494-11e9-8980-ec6100733681.png)

![logo-alt-4](https://user-images.githubusercontent.com/2257024/67273419-c2ad8680-f494-11e9-94df-83576e30b2e1.png)

![logo-alt-5](https://user-images.githubusercontent.com/2257024/67273427-c8a36780-f494-11e9-9562-a522558d5a22.png)

**Comment by Bonandry** [comment]
![path125](https://user-images.githubusercontent.com/7957697/67276569-48492a80-f4c5-11e9-971b-f58ffffb71f2.png)
la seconda ma il template è questo

**Comment by gusbemacbe** [comment]
Ok, vado ridisegnare.
