### ISSUE TITLE
Minor annoyance: icons sharpness

### ISSUE THREAD

**Issue by DarthWound** [Bonandry/yaru-plus#35]
Hey :)

Nothing big, but maybe you could try to work on that later, icons aren't as crisp as the default Yaru ones. See this side by side comparison screenshot taken in Ubuntu 19.10 _(open in full size)_:

![Capture d’écran de 2019-10-26 12-51-04](https://user-images.githubusercontent.com/1771322/67618633-223bc700-f7f2-11e9-8bb1-3f376bc29efe.png)

_EDIT: display is 1080p_

**Comment by gusbemacbe** [comment]
The `index.theme` was copied from Suru++ Ubuntu which contained a lot and lot of bug, it is why it does not have `apps/32` and `apps/48`, I always told the Italian guy not to copy Suru++ Ubuntu, and I had to spend 4 months, correcting both his repositories. 

I will work on it. But firstly I need to test my template on Void.

**Comment by gusbemacbe** [comment]
Ready, @DarthWound !

**Comment by gusbemacbe** [comment]
I understood now. In his old Yaru++, you can compare:

![image](https://user-images.githubusercontent.com/2257024/67624524-e0b61680-f807-11e9-9d7a-0dca5d500b0a.png)

![image](https://user-images.githubusercontent.com/2257024/67624528-e875bb00-f807-11e9-8bd2-449ba9382ad5.png)

**Comment by gusbemacbe** [comment]
If the new beta commit pleases or satisfies you, we will not redo the "pure 32/48 px" icons/ But if not, I (not the Italian guy) will redo next months.

**Comment by DarthWound** [comment]
Thanks ! Good job.

I'm at work, I'll test the beta and tell you if it seems good tomorrow.

Le 26 oct. 2019 20:57, Gustavo Reis <notifications@github.com> a écrit :

If the new beta commit pleases or satisfies you, we will not redo the "pure 32/48 px" icons/ But if not, I (not the Italian guy) will redo next months.

**Comment by DarthWound** [comment]
Some icons are slightly better, yes :-)

But in the dock for example I don't see any improvements:

![Capture d’écran de 2019-10-27 15-28-50](https://user-images.githubusercontent.com/1771322/67637033-d9117300-f8d6-11e9-8626-02a9e4ed483b.png)

Well, don't worry, it doesn't matter that much, it's just that IMHO default Yaru edges are more clear.  But I prefer having a complete theme for all my programs instead of an inconsistent mix.

**Comment by gusbemacbe** [comment]
> But in the dock for example I don't see any improvements

Which improvements did you not see?

**Comment by DarthWound** [comment]
Well, they are a bit more clear I agree, but look at original Yaru like in my [1st screenshot](https://user-images.githubusercontent.com/1771322/67618633-223bc700-f7f2-11e9-8bb1-3f376bc29efe.png). The default set has more relief, see the edges?

Maybe it was intentional to make Yaru++ icons very flat though? In my head Yaru++ concept was more like "Yaru extended", same as the original but with consistent look for every program.

**Comment by gusbemacbe** [comment]
> Well, they are a bit more clear I agree, but look at original Yaru like in my [1st screenshot](https://user-images.githubusercontent.com/1771322/67618633-223bc700-f7f2-11e9-8bb1-3f376bc29efe.png). The default set has more relief, see the edges?

Yes, I did. But to end the inconsistent mix, do you prefer the icons with edges (original Yaru as in the left of 1st screenshot) or without edges (Yaru++ beta without edges)? Or 32 and 48 px with relief and edges and 64 px and scalable without relief and edges? Or all 24 (maybe or not), 32, 48, 64 and scalable without edges and relief?

**Comment by DarthWound** [comment]
Personally, I'm not against flat/material design, but I usually think it is better if an extended set follow the design principles of its source, except if the source is ugly of course. Ubuntu desktop team keep a bit of relief everywhere, even in Yaru-GTK, with subtle gradients and shadows.

But, as I said I don't mind that much, it was just a suggestion, something for you to think about, I don't know what people prefer and I never ask something only for myself :)

Maybe @Feichtmeier and @clobrano and others could give their opinion on this topic? I know they can't endorse a third-party theme though.

If Yaru++ users and creators prefer the flatter look, I'm totally ok with that! Yaru++ is incredibly essential for Ubuntu users in my opinion.

---

Just a not related request by the way, could you make the nose reflection in the GIMP icon darker than white? Maybe something like `#9f9f9f` for example.

**Comment by gusbemacbe** [comment]
> Personally, I'm not against flat/material design, but I usually think it is better if an extended set follow the design principles of its source, except if the source is ugly of course.

To be honest quite, I and the Italian guy (author of this repository) find 32px and 48px icons (edges and relief) very ugly, so we replace them with 64px or scalable icons. But I am not sure that the users of Yaru++ want our icons theme to be exactly like Canonical's Yaru or prefer the icons theme without edges and relief.

> Maybe @Feichtmeier and @clobrano and others could give their opinion on this topic? I know they can't endorse a third-party theme though.

Yes, they can not add, it is why their icons theme is licenced under CC BY-SA/GPL3, then we can fork it and add how many icons we want. I know that Canonical and GNOME developers are against it due to that letter in which criticises the customisation. 

Be aware that I have been once a contributor of Canonical's Yaru. :-). Check https://github.com/ubuntu/yaru/commits?author=gusbemacbe. 

> Just a not related request by the way, could you make the nose reflection in the GIMP icon darker than white? Maybe something like #9f9f9f for example.

The 16px or scalable icon?

**Comment by DarthWound** [comment]
The scalable icon.

**Comment by gusbemacbe** [comment]
I will ask @Bonandry.

@Bonandry, puoi rendere più scuro il riflesso del naso nell'icona di GIMP con il colore di #9f9f9f?

**Comment by clobrano** [comment]
>  I know that Canonical and GNOME developers are against it due [to that letter in which criticises the customisation](https://www.omgubuntu.co.uk/2019/05/open-letter-stop-gtk-theming-distros).

LOL, the letter is mainly against Canonical :D

**Comment by Bonandry** [comment]
@gusbemacbe OK, fatto

**Comment by gusbemacbe** [comment]
Hi @DarthWound !

As @Bonandry wants to keep the sharpened icons in the Yaru++, I have just created the new theme `Yaru++ Smooth`, which does not contain sharpened icons. Please use it from the branch `gusbemacbe`. If you need a dark theme without sharpened icons, please let me know.

**Comment by DarthWound** [comment]
Awesome, thanks! Sorry for late reply, had a lot of work IRL :-)

**Comment by gusbemacbe** [comment]
@DarthWound 

You're welcome. Please check the FRench translation in `index.theme`, I am not sure if my French translation is correct, because I did not find the right words for "sharpness" and "smoothness".

**Comment by DarthWound** [comment]
The french for "smooth" is usually "lisse" here. For "sharp" you can use "net" or "précis" in this context.

**Comment by gusbemacbe** [comment]
So sharp icons = icônes nets ou précises and smooth icons = icônes lisses, @DarthWound ?

**Comment by DarthWound** [comment]
Sharp icons -> Icônes nettes
Smooth icons -> Icônes lisses

**Comment by gusbemacbe** [comment]
@DarthWound 

Please test `Yaru++ Smooth` in the branch `gusbemacbe` if it meets your needs.
