### ISSUE TITLE
Gnome shell little triangles/arrow

### ISSUE THREAD

**Issue by Amathadius** [Bonandry/yaru-plus#36]
In Gnome shell menus (status menu, calendar), triangles for roll-up menus or month selection became much bigger and always to the right "play icons".
![Capture d’écran du 2019-10-27 12-30-20](https://user-images.githubusercontent.com/9408075/67637925-c20e5900-f8b5-11e9-88e5-867351dae35d.png)
![Capture d’écran du 2019-10-27 12-25-56](https://user-images.githubusercontent.com/9408075/67637926-c5a1e000-f8b5-11e9-8ce1-2864f79cc0c8.png)

**Comment by gusbemacbe** [comment]
Hello @Amathadius!

I have already fixed it a week ago after @DarthWound having reported. 

Upgrade the latest version.

**Comment by Amathadius** [comment]
I upgrade everyday, but, this morning, after this comment, the issue is actually fixed.

**Comment by gusbemacbe** [comment]
Hey @Amathadius!

As you are an Arch Linux user, I have released an official AUR of `yaru-plus-git` yesterday.
