### ISSUE TITLE
Icon set has consistency issues in Linux Mint XFCE and especially within Whisker Menu

### ISSUE THREAD

**Issue by Baemir** [Bonandry/yaru-plus#37]
![Screenshot_2019-11-17_02-58-09](https://user-images.githubusercontent.com/7771304/69003928-64d05b00-08e9-11ea-98de-6dd616ef02f6.png)

Basically what the title reads. One of the categories doesn't have a monotone icon, nor does Bulk Rename. Other apps that come by default on Linux Mint XFCE and don't have icons are Backup Tool, Timeshift, Redshift, Pix, Desktop Settings, CompizConfig, Preferred Applications, Login Window, and LM's own "Welcome Screen". Additionally, the icons for apps (not categories) are oversized and take up too much space compared to the text - even if you go into WhiskerMenu's properties and scale them down, they still have zero padding and fit very tightly.

**Comment by gusbemacbe** [comment]
Hello @Baemir !

Please @btd1337's [icons missing script](https://github.com/btd1337/icons-missing-script) and send the ready list of missed icons here.

**Comment by gusbemacbe** [comment]
No need, @Baemir! I installed Linux Mint and extracted missed icons.

Ciao @Bonandry !

Per favore, fa' queste icone perdute:

- [ ] **CompizConfig Settings Manager**
Comment=Configure Compiz with CompizConfig
Comment[it]=Configurare Compiz con CompizConfig
Icon=ccsm
[Icon Link](https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Compiz_logo.svg/640px-Compiz_logo.svg.png?1574103361242)

- [ ] **compton**
Comment=A X compositor
Comment[it]=Un compositore X.
Icon=compton
[Icon Link](https://github.com/chjj/compton/blob/master/media/compton.svg)

- [ ] **Reactivate HP LaserJet 1018/1020 after reloading paper**
Comment=Click the button in this program when your printer ran out of paper and you have refilled the paper
Comment[it]=Fare clic sul pulsante in questo programma quando la stampante ha esaurito la carta e la carta è stata ricaricata
Icon=/usr/share/pixmaps/hplj1020_icon.png

@Baemir, this icon already exists in the Yaru++ icons, but the icon of HP Printer is hardcored, you have to modify manually. 
@Bonandry, non fa quest'icona perché lei già esiste. 

- [ ] **Login Window**
Comment=Configure the login window
Comment[it]=Configurare la finestra di accesso
Icon=lightdm-settings
[Icon Link](https://github.com/linuxmint/lightdm-settings/blob/master/usr/share/icons/hicolor/48x48/apps/lightdm-settings.png)

- [ ] **Backup Tool**
Comment=Make a backup of your `home` directory
Comment[it]=Esegui un backup della tua cartella `home`
Icon=mintbackup
[Icon Link](https://github.com/linuxmint/mintbackup/blob/master/usr/share/icons/hicolor/scalable/apps/mintbackup.svg)

- [ ] **Welcome Screen**
Comment=Introduction to Linux Mint
Comment[it]=Introduzione a Linux Mint
Icon=mintwelcome
[Icon Link](https://github.com/linuxmint/mintwelcome/blob/master/usr/share/icons/hicolor/scalable/apps/mintwelcome.svg)

- [ ] **Pix**  | **Visualizzatore immagini**
Comment=View and organize your images
Comment[it]=Visualizza e organizza le proprie immagini
Icon=pix
[Icon Link](https://github.com/linuxmint/pix/blob/master/data/icons/pix.svg)

- [ ] **Import with Pix**  | **Strumento di importazione foto**
Comment=Import the photos on your camera card
Comment[it]=Importa le foto dalla scheda della fotocamera
Icon=pix
[Icon Link](https://github.com/linuxmint/pix/blob/master/data/icons/pix.svg)

- [ ] **Python (v2.7)**
Comment=Python Interpreter (v2.7)
Icon=/usr/share/pixmaps/python2.7.xpm

@Bonandry, crea un collegamento simbolico di python.svg per python2.7.svg
@Baemir , this Python 2.7 icon is ahrdcored, you have to modify manually.

- [ ] **Python (v3.6)**
Comment=Python Interpreter (v3.6)
Icon=/usr/share/pixmaps/python3.6.xpm

@Bonandry, crea un collegamento simbolico di python.svg per python2.7.svg
@Baemir , this Python 2.7 icon is ahrdcored, you have to modify manually.

- [ ] **Redshift**  | **Regolazione della temperatura del colore**
Comment=Color temperature adjustment tool
Comment[it]=Strumento per la regolazione della temperatura del colore
Icon=redshift
[Icon Link](http://jonls.dk/assets/redshift-icon-256.png)

- [ ] **Redshift**  | **Regolazione della temperatura del colore**
Comment=Color temperature adjustment tool
Comment[it]=Strumento per la regolazione della temperatura del colore
Icon=redshift
[Icon Link](http://jonls.dk/assets/redshift-icon-256.png)

- [ ] **Bulk Rename**  | **Bulk Rename**
Comment=Rename Multiple Files
Comment[it]=Rinomina più file
Icon=Thunar
[Icon Link](https://github.com/xfce-mirror/thunar/blob/master/icons/64x64/Thunar.png)

- [ ] **Thunar File Manager**  | **Gestore di file**
Comment=Browse the filesystem with the file manager
Comment[it]=Esplora il file system con il gestore di file
Icon=Thunar
[Icon Link](https://github.com/xfce-mirror/thunar/blob/master/icons/64x64/Thunar.png)

- [ ] **Open Folder with Thunar**  | **Apri cartella**
Comment=Open the specified folders in Thunar
Comment[it]=Apre le cartelle specificate con Thunar
Icon=Thunar
[Icon Link](https://github.com/xfce-mirror/thunar/blob/master/icons/64x64/Thunar.png)

- [ ] **Timeshift**
Comment=System Restore Utility
Icon=timeshift
[Icon Link](https://raw.githubusercontent.com/teejee2008/timeshift/master/icons/timeshift.png)

**Comment by Bonandry** [comment]
FATTE

**Comment by gusbemacbe** [comment]
@Bonandry 

L'icona di `ccsm` sta rotta. 

![image](https://user-images.githubusercontent.com/2257024/69152120-a6643000-0aba-11ea-9156-811a37b1a1aa.png)

**Comment by gusbemacbe** [comment]
@Bonandry 

Funziona, ma 4 icone sono monocromatiche:

![image](https://user-images.githubusercontent.com/2257024/69156793-c13aa280-0ac2-11ea-99ae-5d95d7937d10.png)

- Portale (Portal): `applications-system`, `applications-system-symbolic`
- Applicazioni Preferite (Preferred APplications): `preferences-desktop-default-applications`
- Dove sono io? (Where am I?): `mark-location`, `mark-location-symbolic`
- Uscire dalla sessione (Log out): `system-log-out`

Come due icone utilizzano il suffisso `-symbolic`, @Baemir deve modificare i file `.desktop` manualmente sulla cartella `~/.local/share/applications`, ma se gli utenti sono troppo pigri, aggiungiamo le icone con questo suffisso, per esempio:

- 16, scalable; applications-system-symbolic, mark-location-symbolic
- symbolic; applications-system-symbolic-symbolic, mark-location-symbolic-symbolic

**Comment by Bonandry** [comment]
ho aggiunto
applications-system-symbolic
preferences-desktop-default-applications
mark-location-symbolic
system-log-out

**Comment by Bonandry** [comment]
> ccsm

penso di avere corretto
