### ISSUE TITLE
Fare 4 nuove icone colorite

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#41]
Ciao @Bonandry 

Per favore fare le icone colorite, in puro stile di Yaru++, in seguita:

- chiave inglese
- educazione (cappello di laurea)
- martello
- scienze

Inviamele qui.

**Comment by Bonandry** [comment]
[icons.zip](https://github.com/Bonandry/yaru-plus/files/4177199/icons.zip)
