### ISSUE TITLE
Fare icone monocromatiche e colorite di dispositivi

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#43]
Ciao @Bonandry !

Per favore, fare tredici icone monocromatiche e diciassette colorite in pure stile di Yaru++.

Osserva che, nella cartella `scalable`:
- `multimedia-player-apple-ipod-touch` deve essere la forma d'iPod touch (vedi l'[immagine](https://www.did.ie/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/v/mvhv2bta_1.jpg));
- `multimedia-player` deve essere la forma d'iPod shuffle (vedi l'[immagine](https://www.imore.com/sites/imore.com/files/topic_images/2014/topic_ipod_shuffle.png));
- `smartphone` deve essere la forma di telefono degli anni 1990 e coppia la mia icona d'Adwaita++, ecco l'anteprima:

![immagine](https://user-images.githubusercontent.com/2257024/74122789-21fde680-4bab-11ea-8b41-c35e6f448a9d.png)

**Comment by gusbemacbe** [comment]
Ecco il pacchetto per fare: 
[Fare.zip](https://github.com/Bonandry/yaru-plus/files/4179111/Fare.zip)

**Comment by Bonandry** [comment]
[fatte.zip](https://github.com/Bonandry/yaru-plus/files/4180063/fatte.zip)

**Comment by gusbemacbe** [comment]
@Bonandry 

L'icona `smartphone` colorita sta sbagliata. Ti ho detto che lei deve essere la forma del smartphone degli anni ‘90.

**Comment by Bonandry** [comment]
è un modello del 1989 :D

**Comment by Bonandry** [comment]
[smartphone.zip](https://github.com/Bonandry/yaru-plus/files/4180343/smartphone.zip)

**Comment by gusbemacbe** [comment]
Perfetto. Grazie. Farò questo pomeriggio.
