### ISSUE TITLE
mpv icons

### ISSUE THREAD

**Issue by Amathadius** [Bonandry/yaru-plus#45]
mpv icons makes no sense. The scalable version is square and the small one is a music note. In addition to the fact that the versions are unrelated, the logo of mpv, a video player, is a "play" in a purple circle. The scalable version still plays, but I don't understand why the small version is a music note.

**Comment by Bonandry** [comment]
thanks for the report, I am working on a new version of Yaru-plus

**Comment by gusbemacbe** [comment]
HI @Amathadius 

:gb: Added icon of MPV, redesigned by @Bonandry, to the branch `gusbemacbe`. 
:fr: Ajouté icône de MPV, redéssinée pour @Bonandry, à la *branch* `gusbemacbe.
:it: Aggiornata icona di MPV, ridisegnata da @Bonandry, alla *branch* `gusbemacbe`. 
:brazil: Adicionado ícone de MPV, redesenhado por @Bonandry, à *branch* `gusbemacbe`.
