### ISSUE TITLE
[Icon request] Pyzo

### ISSUE THREAD

**Issue by filman230** [Bonandry/yaru-plus#46]
Hello! I'd like to request an icon for Pyzo:

- App Name : "Pyzo"
- Icon Name : "pyzologo"
- Description : "Interactive editor for scientific Python"
- Webpage : https://pyzo.org/
- Original Icon
![pyzologo](https://user-images.githubusercontent.com/23081789/79230770-66d12280-7e65-11ea-8fbb-aee2f5d84352.png)

I manually made a svg version some time ago, here it is if you want it:
https://gist.github.com/filman230/f0c0e1ce87165ea3802458b609263059

**Comment by Bonandry** [comment]
thanks, it will be in the next release
![Schermata da 2020-04-16 18-27-29](https://user-images.githubusercontent.com/7957697/79482150-b142d280-8010-11ea-851b-4207665a6064.png)

**Comment by gusbemacbe** [comment]
Hello @filman230 

:gb:  Added icon of MPV, redesigned by @Bonandry, to the branch gusbemacbe. **Do not use the branch `beta` which is unstable.** 
:fr: Ajouté icône de MPV, redéssinée pour @Bonandry, à la branch gusbemacbe. **N'utilisez pas la _branch_ `beta` qui est instable.**
:it: Aggiornata icona di MPV, ridisegnata da @Bonandry, alla branch gusbemacbe. **Non usare la _branch_ `beta` che è instabile.**
:brazil: Adicionado ícone de MPV, redesenhado por @Bonandry, à branch gusbemacbe. **Não use a _branch_ `beta` que é instável.**
