### ISSUE TITLE
Some applications changed their icons name

### ISSUE THREAD

**Issue by filman230** [Bonandry/yaru-plus#47]
gnome-mpv was renamed celluloid so the icon name was changed. A symbolic link pointing from "gnome-mpv" to the new icon name "io.github.celluloid_player.Celluloid" should be added.

**Comment by Bonandry** [comment]
thanks, it will be in the next release

**Comment by filman230** [comment]
I found other programs that changed their icons name:
gthumb -> org.gnome.gThumb
pdfarranger -> com.github.jeromerobert.pdfarranger

**Comment by Bonandry** [comment]
thanks, it will be in the next release (y)

**Comment by gusbemacbe** [comment]
Hello @filman230 

:gb:  Added icons of GThumb and PDF Arranger, redesigned by @Bonandry, to the branch gusbemacbe. **Do not use the branch `beta` which is unstable.** 
:fr: Ajoutées icônes de GThumb et PDF Arranger, redéssinées pour @Bonandry, à la branch gusbemacbe. **N'utilisez pas la _branch_ `beta` qui est instable.**
:it: Aggiornate icone di GThumb e PDF Arranger, ridisegnate da @Bonandry, alla branch gusbemacbe. **Non usare la _branch_ `beta` che è instabile.**
:brazil: Adicionados ícones de GThumb e PDF Arranger, redesenhados por @Bonandry, à branch gusbemacbe. **Não use a _branch_ `beta` que é instável.**
