### ISSUE TITLE
Icon request - Cool Retro Term

### ISSUE THREAD

**Issue by DanyGee** [Bonandry/yaru-plus#50]
Appname: cool-retro-term
Icon Name: cool-retro-term
Description: Rock your terminal cool retro style
Webpage: https://github.com/Swordfish90/cool-retro-term
Original Icon:
![cool-retro-term](https://user-images.githubusercontent.com/26818551/81731807-c257f580-948f-11ea-899a-150b8aa0c50e.png)

**Comment by gusbemacbe** [comment]
Ciao @Bonandry!

Per favore, fa un'icona di quest'applicazione.

**Comment by gusbemacbe** [comment]
Hello @DanyGee !

:gb: Icons of Cool Retro Term, designed by @Bonandry, have been added.
:de: Die Ikonen von Cool Retro Term, von @Bonandry gemachte, wurden hinzugefügt. 
:fr:  Icônes de Cool Retro Term, dessinées par @Bonandry, ont été ajoutées. 
:it: Icone di Cool Retro Term, disegnate da @Bonandry, sono state aggiungte. 
:brazil: Ícones de Cool Retro Term, feitas por @Bonandry, foram adicionadas.
:poland: Ikony aplikacji Cool Retro Term, wykonane przez @Bonandry, zostały dodane.
