### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by speltriao** [Bonandry/yaru-plus#51]
Ciao! Almeno adesso io non trovo i seguenti iconi:

- [x] Celluloid
- [x] Drawing
- [x] Gnome Extensions (nuovo in 3.36)
- [x] OnlyOffice
- [x] Microsoft Teams
- [x] Visual Studio Code

E anche non lo so se Yaru++ è compatibile com applicazioni Flatpak.

Grazie

**Comment by gusbemacbe** [comment]
> E anche non lo so se Yaru++ è compatibile com applicazioni Flatpak.

Tutta la famiglia Suru++ (Adwaita, Suru e Yaru) è compatibile con le icone delle applicazioni Flatpak se tu utilizzi il parameto `--user`. Non sono compatibili con quelle delle applicazioni Snapcraft perché loro sono fissamente codificate.

**Comment by gusbemacbe** [comment]
Ciao @speltriao !

Puoi utilizzare lo script di @btd1337: https://github.com/btd1337/icons-missing-script? Lo script di @btd1337 extrae i nomi delle applicazioni Flatpak e egenera la lista di icone perdute qui. A esempio: https://github.com/Bonandry/yaru-plus/issues/38.

**Comment by gusbemacbe** [comment]
@speltriao, le icone di Celluloid e GNOME Extensions sono state aggiunge, ma purtroppo quale l'applicazione "Drawing stai utilizzando. Le altre applicazioni, devo installarle via Flatpak.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry!

Fa un'icona di [Drawing](https://flathub.org/apps/details/com.github.maoschanz.drawing) con un nome di `drawing`. E fa un collegamento simbolico di `drawing` al nuovo file `om.github.maoschanz.drawing`. 

![image](https://user-images.githubusercontent.com/2257024/86646540-b8e19a00-bfb5-11ea-8c8a-8edfd775f61e.png)

**Comment by gusbemacbe** [comment]
@speltriao 

L'icona di `Visual Studio Code` della Flatpak già esiste sulla *branch* ` gusbemacbe` prima.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

Fa un'icona di [`OnlyOffice`](https://flathub.org/apps/details/org.onlyoffice.desktopeditors), in pure stile di Yaru, con un nome di `onlyoffice` e fa un collegamento simbolico al nuovo file `org.onlyoffice.desktopeditors`.

![image](https://user-images.githubusercontent.com/2257024/86647653-9c922d00-bfb6-11ea-953d-584632423e8a.png)

**Comment by gusbemacbe** [comment]
@Bonandry 

Fa un'icona di [`Microsoft Teams`](https://flathub.org/apps/details/com.microsoft.Teams) con un'icona di `teams` e fa un collegamento simbolico di `teams` ai nuovi tre file `teams-for-linux`, `com.microsoft.Teams` e `com.github.IsmaelMartinez.teams_for_linux`.

![image](https://user-images.githubusercontent.com/2257024/86648949-b1bb8b80-bfb7-11ea-966d-00b87a4feba7.png)

Senza lo emblema `Preview`.

**Comment by Bonandry** [comment]
fatte

**Comment by gusbemacbe** [comment]
@Bonandry, molte grazie, scusami per la mia assenza, io ero molto malato nausea e vomito. 
@speltriao, tutte le icone aggiunte alla *branch* `gusbemacbe`. :wink:
