### ISSUE TITLE
Icon Request - Alacritty

### ISSUE THREAD

**Issue by leesiongchan** [Bonandry/yaru-plus#52]
App Name: Alacritty
    Icon Name: Alacritty.svg
    Description: A cross-platform, GPU enhanced terminal emulator
    Webpage (optional): https://github.com/alacritty/alacritty
    Original Icon: 
![alacritty_Alacritty](https://user-images.githubusercontent.com/324418/84812423-fac79200-b040-11ea-8895-a217c09e0cf1.png)

**Comment by gusbemacbe** [comment]
Hello @leesiongchan  !

gb Icons of Alacritty, designed by @Bonandry, have been added.
de Die Ikonen von Alacritty, von @Bonandry gemachte, wurden hinzugefügt.
fr Icônes de , dessinées par @Bonandry, ont été ajoutées.
it Icone di Alacritty, disegnate da @Bonandry, sono state aggiungte.
brazil Ícones de Alacritty , feitas por @Bonandry, foram adicionadas.
poland Ikony aplikacji Alacritty, wykonane przez @Bonandry, zostały dodane.
