### ISSUE TITLE
Non utilizzare la maschera d'ombra

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#54]
Ciao @Bonandry !

Per favore, sostituisce la maschera di queste icone:

![image](https://user-images.githubusercontent.com/2257024/87138860-6f26d700-c275-11ea-871d-d3a2ab9c5084.png)

**Comment by gusbemacbe** [comment]
@Bonandry, anche corregge queste icone:

![image](https://user-images.githubusercontent.com/2257024/87215738-dbeeaf80-c30f-11ea-8266-2d5e32190ec6.png)

**Comment by gusbemacbe** [comment]
@Bonandry, anche:

![image](https://user-images.githubusercontent.com/2257024/87216062-6df7b780-c312-11ea-8cca-6ce06114659e.png)

**Comment by gusbemacbe** [comment]
![image](https://user-images.githubusercontent.com/2257024/87216411-d8f6bd80-c315-11ea-994c-ba06af9cd501.png)

**Comment by gusbemacbe** [comment]
Ah, più icone:

![image](https://user-images.githubusercontent.com/2257024/87216659-22e0a300-c318-11ea-8996-eb4adc63f953.png)

**Comment by Bonandry** [comment]
![Schermata da 2020-07-11 17-39-18](https://user-images.githubusercontent.com/7957697/87227838-b0b2a180-c39d-11ea-8d16-6f57e5444f5a.png)
![Schermata da 2020-07-11 17-38-08](https://user-images.githubusercontent.com/7957697/87227839-b1e3ce80-c39d-11ea-9d38-6cef5e510334.png)
@gusbemacbe non riesco a trovare la maschera

**Comment by gusbemacbe** [comment]
Ciao @Bonandry, vado trovare e rimouvere.

**Comment by gusbemacbe** [comment]
Ah, vedi se trovi la maschera sull'Inkscape, @Bonandry. Figma solo risolve il problema.

**Comment by Bonandry** [comment]
![Schermata da 2020-07-12 08-30-40](https://user-images.githubusercontent.com/7957697/87240447-02007680-c41a-11ea-834f-9566c60ba5fc.png)
niente anche su inkscape
