### ISSUE TITLE
Aggiornare le icone di VSCode e VSCode Insiders

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#55]
Ciao @Bonandry !

Per favore, aggiornare le icone di VSCode e VSCode Insiders, ma in pure stile di Yaru. Microsoft ha fatto le nuove icone:

- file `vscode`:

<img height="100" src="https://user-images.githubusercontent.com/2257024/87193249-afff0a00-c2ce-11ea-953a-e6074380c35a.png"/>

- file `vscode-insiders`:

<img height="100" src="https://user-images.githubusercontent.com/2257024/87193369-f0f71e80-c2ce-11ea-8fad-8853595b4a8b.png"/>

- Le icone di 16px e simboliche:

<img height="100" src="https://user-images.githubusercontent.com/2257024/87193475-2c91e880-c2cf-11ea-8b20-331031f151b1.png">

**Comment by Bonandry** [comment]
Fatto
