### ISSUE TITLE
Icone mancante

### ISSUE THREAD

**Issue by speltriao** [Bonandry/yaru-plus#63]
Ciao! Grazie per il lavoro con Yaru++. Mi piace!

Ho scoperto alcuni icone (apparentemente) mancante: 

Python Idle 3 (https://docs.python.org/3/library/idle.html) 
Foliate (https://johnfactotum.github.io/foliate/)
Tux Guitar (http://www.tuxguitar.com.ar/)

**Comment by gusbemacbe** [comment]
Ciao @speltriao !

Le icone di Picard e MPV sono già presenti nelli tema di icone. Per favore utilizza lo script di @btd1337: https://github.com/btd1337/icons-missing-script.

**Comment by speltriao** [comment]
Aggiornato! Dunque, manca solo Foliate.

**Comment by speltriao** [comment]
Aggiornato!

**Comment by gusbemacbe** [comment]
@Bonandry, per favore fa true ícone mancante.

**Comment by Bonandry** [comment]
![Schermata da 2020-09-08 09-02-52](https://user-images.githubusercontent.com/7957697/92443837-5a51bb80-f1b2-11ea-898e-e2002eb8b80f.png)

**Comment by gusbemacbe** [comment]
@Bonandry 

Per favore, crea l'icona di Foliate con il nome di "foliate", e collegala simbolicamente all'icona con il lungo nome.

**Comment by Bonandry** [comment]
fatto
