### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by coxackie** [Bonandry/yaru-plus#64]
Hi guys,

 great work - I use this set to complement Yaru, as it misses a lot of icons. Some further ones that I think are missing to consider

 - Zoom desktop
 - ScummVM
 - Julia
 - Zotero

**Comment by Bonandry** [comment]
hi, i will do them but you have to tell me the exact name of the icon

**Comment by coxackie** [comment]
Many thanks. Looking at the `Icon` entry of the `.desktop` files, I get, respectively:

- `Zoom.png`
- `scummvm`
- `julia`
- `zotero`

Not sure why the ".png" in the first, though...

**Comment by Bonandry** [comment]
add in beta 
![Schermata da 2020-10-27 15-25-56](https://user-images.githubusercontent.com/7957697/97315290-dab6a380-1868-11eb-85c4-5f7b1e9a7e8c.png)

**Comment by Bonandry** [comment]
@gusbemacbe

**Comment by coxackie** [comment]
That looks quite cool - thanks so much!

 Could you please be updating also the Yaru++-Minimal folder with everything new you make (and have made)? I am pulling the beta git, and want to be complementing Yaru with Yaru++-Minimal, so this would be very helpful...

**Comment by gusbemacbe** [comment]
Ciao @Bonandry,

Crea l'icona con il nome di `zoom` e ricollegalla con il file `Zoom`.

**Comment by gusbemacbe** [comment]
Chairete @coxackie 

Only I can upgrade Yaru++ Minimal. I'll do on weekend. Andrea is just a designer and does not want to mess the symlinks.

This week I can't do mow because I'm working with a new site for a client.

Eucharisto poly!

**Comment by coxackie** [comment]
many thanks @gusbemacbe - I will wait for the weekend to come. I use Arch Linux, and I was thinking of also creating an AUR for Yaru plus minimal, but I saw you are maintaining [this](https://aur.archlinux.org/packages/yaru-plus-git/) already.

 Your knowledge of Greek is also impressive. Ευχαριστώ!

**Comment by Bonandry** [comment]
> Ciao @Bonandry,
> 
> Crea l'icona con il nome di `zoom` e ricollegalla con il file `Zoom`.
fatto

**Comment by coxackie** [comment]
@gusbemacbe any updates on pushing the new icons to Yaru++ Minimal?

**Comment by gusbemacbe** [comment]
Χαίρετε και καλησπέρα Κοστας @coxackie !

Sorry, I have been working a lot, as my boss was too slow and late to deliver me all the needed recourses for his client's website. I have just uploaded @Bonandry's icons to the branch `gusbemacbe`. I will merge the branch `gusbemacbe` into the branch `nightly`, which into the official `master`. You can download the icons folders from the branch `gusbemacbe` to replace the current icons folders at the directory `~/.local/share/icons` (KDE and others).
