### ISSUE TITLE
Due icone mancante

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/yaru-plus#65]
Ciao @Bonandry !

Per favore fa due icone di 16px (monocromatiche per Yaru++ e colorite per Yaru++ Colore), 48px e scalable:

- Microsoft Edge Dev (`microsoft-edge-dev`)
- Onvim 2 (`onivim`, e collegala alle icone con i nome di `onivim2`, `Onivim2` e `appimagekit_5b96b63fa5dca1e558c7bafdb4a6d4b3_Onivim2`) 

![microsoft-edge-dev](https://user-images.githubusercontent.com/2257024/101303782-97fbca00-381d-11eb-9997-e5f985188419.png) <img alt="onivim" height="48px" src="https://user-images.githubusercontent.com/2257024/101303878-d85b4800-381d-11eb-802d-58237433fa1b.png"/>

**Comment by Bonandry** [comment]
Ciao @gusbemacbe  
Ho fatto le icone e le ho messe in un file compresso dal nome Edge e Onvim 
![Schermata da 2020-12-07 14-24-00](https://user-images.githubusercontent.com/7957697/101356250-12693000-3898-11eb-8495-14f86a19d04c.png)
