### ISSUE TITLE
Request: Icon for neovim

### ISSUE THREAD

**Issue by coxackie** [Bonandry/yaru-plus#71]
for reference:

https://github.com/neovim/neovim

I think it just needs a bit of resizing, to be honest; otherwise, the style fits yaru.

**Comment by Bonandry** [comment]
[apps.zip](https://github.com/Bonandry/yaru-plus/files/6289469/apps.zip)
extract the file, put each icon in its folder and type if it is OK

**Comment by Bonandry** [comment]
![Schermata da 2021-04-10 10-03-40](https://user-images.githubusercontent.com/7957697/114263136-2064c400-99e4-11eb-92da-8e2f36164da7.png)

**Comment by coxackie** [comment]
great work - thanks a lot!
