### ISSUE TITLE
[Request] Tilix and Geary mail

### ISSUE THREAD

**Issue by Amathadius** [Bonandry/yaru-plus#8]

**Comment by Bonandry** [comment]
Hi Amathadius, these icons are already present

**Comment by Amathadius** [comment]
I didn't know. Sorry.
In this case, there's an issue.
The "real" name for Tilix icon is : "com.gexperts.Tilix"
For Geary, there's something similar but I can't recall it for now.

**Comment by gusbemacbe** [comment]
How did you install Geary? Via Flatpak or via Snap?

If via Snap, then Snap apps icons are hardcoded.

If via Flatpak, go to `~/.local/share/flatpak`.

If installed via `opt`, go to `~/.local/share/applications`.

**Comment by Bonandry** [comment]
org.gnome.Geary
com.gexperts.Tilix
will be present at the next release
